### ISSUE TITLE
"items doesn't support maps" error

### ISSUE THREAD

**Issue by roytman** [ribice/golang-swaggerui-example#1]
Hi @ribice, thanks for the blog and the example project.
I work on swagger documentation of my project, so your explanations and examples are very helpful.
In order to practice with go-swagger directives, I cloned your project and tried to recreate swagger definitions:
`swagger generate spec -o ./swagger.json`
The command returned 
`items doesn't support maps`.

The same error I get in my project when I tried to add a `map[string]string` as an `in:body` request parameter. According to the go-swagger documentation it should be OK . 
Is something wrong with my environment or  go-swagger was changed?

My go-swagger version is the:
version: dev
commit: afb97176d2f0d6e47868888ca0f6c5b91cae075f

**Comment by ribice** [comment]
Hi @roytman, generally I think you will get a better response by posting on [go-swagger repo](https://github.com/go-swagger/go-swagger) or on gophers slack, #go-swagger channel.

If you don't get any response there, I'll be happy to help you, but @casualjim does a great job supporting go-swagger.

**Comment by roytman** [comment]
Thanks, will do it

**Comment by roytman** [comment]
Sorry, it was my fault.
